language: android

sudo: false

jdk: oraclejdk8

android:
  components:
    - android-23
    - tools
    - build-tools-23.0.3
    - extra
    - extra-android-m2repository
    - sys-img-armeabi-v7a-google_apis-google-$TARGET

before_script:
  - echo no | android create avd --force -n test --target "Google Inc.:Google APIs:$TARGET" --abi "default/armeabi-v7a" --sdcard 200M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 10
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew -s -PdisablePreDex clean assembleDebug connectedAndroidTest

env:
  global:
    - GRADLE_OPTS="-Xmx4g"
    - ADB_INSTALL_TIMEOUT=15
  matrix:
    - TARGET=17
    - TARGET=19
    - TARGET=21

cache:
  directories:
    - $HOME/.gradle/caches/2.13
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper